spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/deposit_service_database
    username: test
    password: test
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    port: 5672
    host: rabbitmq
    username: test
    password: test
    listener:
      direct:
        default-requeue-rejected: true
