hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account-service/**

        - id: bill-service
          uri: lb://bill-service
          predicates:
            - Path=/bill-service/**

        - id: deposit-service
          uri: lb://deposit-service
          predicates:
            - Path=/deposit/**

        - id: withdraw-service
          uri: lb://withdraw-service
          predicates:
            - Path=/withdraw/**

server:
  port: 8989
