spring:
  cloud:
    config:
      server:
        native:
          search-localtime: classpath:/services
  profiles:
    active: native
  security:
    user:
      password: admin

server:
  port: 8001
